#-------------------------------------------------------------------------
# Travis CI configuration file
#-------------------------------------------------------------------------
#    Pre-build step installs packages for reactjs dependencies
#    Build generates the packed javascript and builds the WAR
#-------------------------------------------------------------------------
#
language: java
jdk:
  - oraclejdk8

# compile javascript
before_script:
 - travis_retry npm install 
 - webpack

# package UI and run
script:
 - ./gradlew test
 - ./gradlew build

# upload new build
after_success:
