/** Define valid action types **/
'use-strict'

export const REQUEST_QUERY_STARTED = 'REQUEST_QUERY_STARTED';
export const REQUEST_QUERY_STOPPED = 'REQUEST_QUERY_STOPPED';
export const REQUEST_QUERY_FAILED = 'REQUEST_QUERY_FAILED';
export const QUERY_STATUS_RUNNING = 'QUERY_STATUS_RUNNING';


